### ISSUE TITLE
что будет если я удалю кэш по тэгу "iblock_id_" . $arParams["IBLOCK_ID"] ? Интересен случай, когда у нас несколько инфоблоков

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#10]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section.php#L53

**Comment by Arsmars88** [comment]
Пока что-то внятное не могу ответить, надо ознакомиться.

**Comment by awg-corp** [comment]
ознакомься)

**Comment by Arsmars88** [comment]
Что-то все равно не могу придти к чему-то. Если удалить кеш, по условию отработает CIBlockSection::GetList, после чего данные снова закешируются и затегируются, в данном случае кеш попадет в папку /bitrix/cache/iblock/catalog/{первые два символа от md5 сериализованного массива $arrFilter}/{ md5 сериализованного массива $arrFilter}/
Не совсем понимаю ремарку по поводу нескольких инфоблоков, вряд ли в $arParams["IBLOCK_ID"] на вход подадут массив.
