### ISSUE TITLE
почему 'LIST' != $arParams['VIEW_MODE'] а не $arParams['VIEW_MODE'] != 'LIST' ?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#11]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/bitrix/catalog.section.list/.default/result_modifier.php#L25

**Comment by Arsmars88** [comment]
На результат это никак не виляет, но я бы написал конечно $arParams['VIEW_MODE'] != 'LIST' , так как мы сравниваем переменную со значением и не значение с переменной, да и с точки зрения восприятия лучше.

**Comment by awg-corp** [comment]
а между `'LIST' == $arParams['VIEW_MODE']` и `$arParams['VIEW_MODE'] == 'LIST'` какая разница с точки зрения использования потом?

**Comment by Arsmars88** [comment]
Мое мнение что разницы никакой, можно рассмотреть вариант если, к примеру кто-то случайно поставить не ==, а =, тогда 'LIST' = $arParams['VIEW_MODE'] выдаст ошибку, а $arParams['VIEW_MODE'] = 'LIST'  - нет.
