### ISSUE TITLE
как можно оптимизировать запрос, порождаемый этой конструкцией?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#12]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/bitrix/catalog.section.list/.default/result_modifier.php#L76

**Comment by Arsmars88** [comment]
возможно как вариант в параметр arFilter необхдимо передать массив используя @ - оператор может использоваться для целочисленных и вещественных данных при передаче набора значений (массива). В этом случае при генерации sql-запроса будет использован sql-оператор IN, насколько мне известно в MYSQL срабатывает быстрее,чем множественные or
