### ISSUE TITLE
каким образом установить модуль миграций и зачем они вообще нужны?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#15]

**Comment by Arsmars88** [comment]
Можно установить через маркетплейс - https://marketplace.1c-bitrix.ru/solutions/sprint.migration/ (Что я и сделал), также у них на гитхабе есть модули.
В целом миграция решает проблемы контроля версий баз данных друг между другом, т.е. все действия, изменяемые её структуру производятся через накаты и откаты, чтобы позволяет как раз контролировать версию бд
