### ISSUE TITLE
почему так лучше тут не делать?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#3]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section_vertical.php#L89

**Comment by Arsmars88** [comment]
Могу предположить из-за дублирования кода в section_horizontal.php.

**Comment by Arsmars88** [comment]
Можно было бы еще проверку на $arParams["IBLOCK_ID"] всадить.

**Comment by awg-corp** [comment]
ну вообще в принципе в шаблонах кэшируемого компонента использование дополнительно кэширования что дает? каки плюсы и минусы?

**Comment by Arsmars88** [comment]
Из плюсов можно выделить то что можно кешировать отдельные данные шаблона компонента, что позволит вызывать другие компоненты в шаблоне.  Из минусов могу выделить большое количество файлов кеша, тут могут возникнуть проблемы с местом на диске.
