### ISSUE TITLE
чем отличаются эти 2 вызова?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#4]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section_vertical.php#L118-L119

**Comment by Arsmars88** [comment]
В первом случае идет подключение класса компонента, от которого можно унаследоваться, либо использовать доступные методы.
Во втором случае собственно идет выполнение работы самого компонента со всеми вытекающими.
