### ISSUE TITLE
опять не перенес шаблон и что это за компонент (за вывод чего отвечает?)

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#5]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section_vertical.php#L120-L121

**Comment by Arsmars88** [comment]
Да, этот компонент по идее нафиг не нужен по условию задачи. Выводит "подарки" к товарам раздела.
