### ISSUE TITLE
как это можно сделать иначе?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#6]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section_vertical.php#L250-L378

**Comment by Arsmars88** [comment]
Возможно не так понял вопрос.
1. Если вопрос по вызову, то можно $arParams для catalog.section инициализировать в отдельный массив, а нужные параметры инициализировать как душе угодно.
2. $intSectionID можно привести к типу и без вызова компонента, он и так известен, либо сделать CIBlockSection::GeList();, если шаблон не нужен.
3. Плюс $component уже содержит в себе arParams, можно это использовать(отсылаясь к п1.)
