### ISSUE TITLE
за что отвечает этот параметр?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#7]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section_vertical.php#L387

**Comment by Arsmars88** [comment]
Не использовал ранее данный параметр, в данном случае, ссылаясь на документацию, отвечу что при отмеченном параметре станут доступны дополнительные поля для выборки рекомендаций к товару.
