### ISSUE TITLE
чем отличаются шаблоны?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#8]
local/templates/test/components/bitrix/catalog/.default/section_vertical.php
local/templates/test/components/bitrix/catalog/.default/section_horizontal.php

**Comment by Arsmars88** [comment]
section_horizontal.php - умный фильтр отображается сверху и горизонтально относительно каталога.
section_vertical.php - умный фильтр отображается справа и вертикально относительно каталога

**Comment by awg-corp** [comment]
сами шаблоны чем отличаются? файлы всмысле

**Comment by Arsmars88** [comment]
Они отличаются компоновкой компонентов, т.е. версткой: от списка классов родительских блоков, до вызова сайдбара в разных местах.
