### ISSUE TITLE
чем вызов $this->addExternalCss отличается от \Bitrix\Main\Page\Asset::addCss ?

### ISSUE THREAD

**Issue by awg-corp** [Arsmars88/awgt#9]
https://github.com/Arsmars88/awgt/blob/9d96b861e4e0fd6612f57ca320263dec02450c41/local/templates/test/components/bitrix/catalog/.default/section.php#L19

**Comment by Arsmars88** [comment]
$this->addExternalCss - метод объекта шаблон и вызывается в шаблоне компонента.

**Comment by awg-corp** [comment]
а если вот на это заменить `\Bitrix\Main\Page\Asset::addCss` что будет?

**Comment by Arsmars88** [comment]
Ничего не изменится=)
